SELECT 
    zip AS `zip`,
    country AS `country`,
    contact_name AS `contact_name`,
    address AS `address`,
    city AS `city`,
    address2 AS `address2`,
    join_date AS `join_date`,
    latitude AS `latitude`,
    county AS `county`,
    `type` AS `type`,
    created_by AS `created_by`,
    url AS `url`,
    phone AS `phone`,
    created_on AS `created_on`,
    last_update AS `last_update`,
    name AS `name`,
    participating AS `participating`,
    id AS `id`,
    state AS `state`,
    email AS `email`,
    parent_facility_id AS `parent_facility_id`,
    longitude AS `longitude`,
    `_airbyte_ab_id` AS `_airbyte_ab_id`,
    `_airbyte_emitted_at` AS `_airbyte_emitted_at`,
    `_airbyte_normalized_at` AS `_airbyte_normalized_at`,
    `_airbyte_facility_hashid` AS `_airbyte_facility_hashid`
FROM {{ source('visits', 'facility') }} 