version: 2

sources:
  - name: visits
    schema: mysql_extracts
    tables:
    - name: comprehensive_encounter_map
    - name: comprehensive_encounter
      columns: 
        - name: id
          tests:
            - unique
        - name: type
          tests:
            - accepted_values:
                values: ['EMERGENCY','UNKNOWN','POST_ACUTE_CARE','INPATIENT','NULL','BEHAVIORAL_HEALTH']
    - name: facility
    - name: patient_diagnosis
    - name: PatientDisability
    - name: PatientEthnicity
    - name: PatientLanguage
    - name: PatientMarital
    - name: PatientRace
    - name: patient_visit_details
    - name: patient_visit_pds_care_provider
    - name: patient_visit