[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.dagster]
module_name = "demo_pipeline"

dependencies = [
    "pip==23",
    "Faker",
    "mysql-connector-python",
    "pandas"
]